using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml;
using TaleWorlds.Library;

namespace CustomSceneCreator.Catalog {
    /// <summary>One scene the editor can open.</summary>
    public class SceneEntry {
        public string Name = "";
        public string Module = "";
        public string Category = "";
        /// <summary>Space-separated level names, exactly as
        /// <c>MissionInitializerRecord.SceneLevels</c> wants them. Empty for single-level scenes.</summary>
        public string Levels = "";
        public bool NoNavMesh;
        public bool NoTerrain;
        public bool NoAtmosphere;

        public string[] LevelNames =>
            string.IsNullOrWhiteSpace(Levels) ? Array.Empty<string>() : Levels.Split(' ');

        /// <summary>Scenes without a navmesh load but no agent can path in them, so the player
        /// cannot walk. Worth saying up front rather than letting it look like a bug.</summary>
        public bool IsWalkable => !NoNavMesh;
    }

    /// <summary>
    /// Plain-English meanings for the upgrade-level names shipped scenes declare.
    ///
    /// A scene is authored as one geometry set with named layers, and the mission decides which
    /// layers to show. That is how a single town scene covers its whole life: an undeveloped
    /// village, a prosperous one, the same place mid-siege, and the same place after a raid.
    /// </summary>
    public static class SceneLevelInfo {
        public static string Describe(string level) {
            switch (level?.ToLowerInvariant()) {
                case "base":     return "foundation geometry - always included";
                case "level_1":  return "settlement development tier 1 (smallest)";
                case "level_2":  return "settlement development tier 2";
                case "level_3":  return "settlement development tier 3 (largest)";
                case "civilian": return "peacetime dressing - stalls, furniture, civilian props";
                case "siege":    return "siege state - barricades, damage, siege equipment";
                case "sally":    return "sally-out variant of the siege layout";
                case "raid":     return "village raid in progress";
                case "burned":   return "post-raid burned-out state";
                default:         return "scene-specific layer";
            }
        }

        /// <summary>Levels that are alternative states of the same place rather than additive
        /// detail. Ticking two of these at once shows both sets of geometry overlapping.</summary>
        public static bool IsExclusiveState(string level) {
            switch (level?.ToLowerInvariant()) {
                case "civilian":
                case "siege":
                case "sally":
                case "raid":
                case "burned":
                    return true;
                default:
                    return false;
            }
        }

        public static bool IsTier(string level) {
            switch (level?.ToLowerInvariant()) {
                case "level_1":
                case "level_2":
                case "level_3":
                    return true;
                default:
                    return false;
            }
        }
    }

    /// <summary>
    /// Loads <c>ModuleData/scene_catalog.xml</c>, generated by <c>tools/build_scene_catalog.ps1</c>
    /// from the local install.
    ///
    /// The catalog is a build artifact rather than a runtime scan because reading 611 scene.xscene
    /// files - several of which are hundreds of kilobytes - is not something to do while the player
    /// waits at a menu.
    /// </summary>
    public static class SceneCatalog {
        private static List<SceneEntry>? _scenes;

        public static IReadOnlyList<SceneEntry> All => _scenes ??= Load();

        public static SceneEntry? Find(string sceneName) =>
            All.FirstOrDefault(s => string.Equals(s.Name, sceneName, StringComparison.OrdinalIgnoreCase));

        public static IEnumerable<string> Categories =>
            All.Select(s => s.Category).Distinct().OrderBy(c => c);

        private static List<SceneEntry> Load() {
            var result = new List<SceneEntry>();
            string path = ResolveCatalogPath();

            if (path.Length == 0 || !File.Exists(path)) {
                TraceLogger.Write(nameof(SceneCatalog),
                    $"scene_catalog.xml not found (looked at '{path}'). " +
                    "Scene browsing will be unavailable; csc.open still works by name.");
                return result;
            }

            try {
                var doc = new XmlDocument();
                doc.Load(path);
                XmlNodeList? nodes = doc.SelectNodes("/SceneCatalog/Scene");
                if (nodes != null) {
                    foreach (XmlNode node in nodes) {
                        XmlElement? el = node as XmlElement;
                        if (el == null) continue;
                        result.Add(new SceneEntry {
                            Name = el.GetAttribute("name"),
                            Module = el.GetAttribute("module"),
                            Category = el.GetAttribute("category"),
                            Levels = el.GetAttribute("levels"),
                            NoNavMesh = el.GetAttribute("noNavMesh") == "true",
                            NoTerrain = el.GetAttribute("noTerrain") == "true",
                            NoAtmosphere = el.GetAttribute("noAtmosphere") == "true",
                        });
                    }
                }
                TraceLogger.Write(nameof(SceneCatalog),
                    $"Loaded {result.Count} scenes from '{path}' " +
                    $"({result.Count(s => !s.IsWalkable)} without a navmesh).");
            } catch (Exception ex) {
                TraceLogger.WriteException(nameof(SceneCatalog), $"Failed to parse '{path}'", ex);
            }

            return result;
        }

        private static string ResolveCatalogPath() {
            // Module layout differs between a built Dist folder and a deployed module, so try both
            // rather than assuming one.
            foreach (string candidate in new[] {
                Path.Combine(BasePath.Name, "Modules", "CustomSceneCreator", "ModuleData", "scene_catalog.xml"),
                Path.Combine(BasePath.Name, "Modules", "CustomSceneCreator", "_Module", "ModuleData", "scene_catalog.xml"),
            }) {
                if (File.Exists(candidate)) return candidate;
            }
            return Path.Combine(BasePath.Name, "Modules", "CustomSceneCreator", "ModuleData", "scene_catalog.xml");
        }
    }
}
