using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using TaleWorlds.Library;
using IOPath = System.IO.Path;

namespace CustomSceneCreator.Catalog {
    /// <summary>A value shipped scenes use for a variable, offered as a preset.</summary>
    public class ScriptPreset {
        public string Text = "";
        /// <summary>How many times shipped scenes set the variable to this.</summary>
        public int Uses;
        /// <summary>How many distinct scenes use it - the measure of how general a value is.</summary>
        public int Scenes;
    }

    /// <summary>One variable a script takes, as observed in shipped scenes.</summary>
    public class ScriptVariable {
        public string Name = "";
        /// <summary>bool, float, string or entity. Inferred from observed values by the generator.</summary>
        public string Type = "string";
        public string Default = "";
        public string Samples = "";
        public int Uses;

        /// <summary>
        /// Values shipped scenes actually use for this variable, most-used first.
        ///
        /// These exist because a string variable is usually not free text at all - "Event Path" wants
        /// one of a fixed set of FMOD event names, and there is no way to guess one. The real list
        /// lives in sound banks the game never exposes (module_sounds.xml is only an example
        /// template), so the shipped scenes are the only place the working values can be read from.
        /// Empty for variables with no repeated values worth offering.
        /// </summary>
        public List<ScriptPreset> Presets = new();

        public bool HasPresets => Presets.Count > 0;

        /// <summary>
        /// A GUID pointing at another entity - AnimationPoint's PairEntity is the common case. Shown
        /// read-only for now: editing one properly needs a click-to-pick-target mode, and a text box
        /// inviting a hand-typed GUID would be worse than admitting the gap.
        /// </summary>
        public bool IsEntityReference => Type == "entity";
    }

    public class ScriptDefinition {
        public string Name = "";
        public int Uses;
        public string Category = "Other";
        public List<ScriptVariable> Variables = new();

        /// <summary>
        /// False for scripts that expect a mission type this editor does not run. They still attach
        /// and still export - only the live preview is unavailable.
        /// </summary>
        public bool CanPreview => Editing.ScriptAttacher.CanPreview(Name);
    }

    /// <summary>
    /// Loads <c>ModuleData/script_catalog.xml</c>, generated by <c>tools/build_script_catalog.ps1</c>
    /// from the shipped scenes.
    ///
    /// Ordered by how often shipped scenes actually attach each script, because the distribution is
    /// wildly uneven - AnimationPoint is used 34,187 times and the tail is in single digits.
    /// Alphabetical order would bury everything worth reaching under things nobody has ever used.
    /// </summary>
    public static class ScriptCatalog {
        private static List<ScriptDefinition>? _scripts;

        public static IReadOnlyList<ScriptDefinition> All => _scripts ??= Load();

        public static IEnumerable<string> Categories =>
            All.Select(s => s.Category).Distinct().OrderBy(c => c);

        public static ScriptDefinition? Find(string name) =>
            All.FirstOrDefault(s => string.Equals(s.Name, name, StringComparison.OrdinalIgnoreCase));

        /// <summary>
        /// Grouped by what a script is FOR, derived from its name. There is no structural grouping in
        /// the data to borrow - the scenes only record names - so this is the one place the catalog
        /// needs an opinion rather than a measurement.
        /// </summary>
        private static readonly (string Category, string[] Keywords)[] CategoryRules = {
            ("Animation & Pose",  new[] { "animation", "pose", "skeleton", "handmorph", "morph" }),
            ("Lighting & Effects",new[] { "light", "particle", "burning", "fire", "lightning", "decal", "emission", "trajectory" }),
            ("Sound",             new[] { "sound", "audio", "music" }),
            ("Spawners",          new[] { "spawner", "spawnpoint", "spawnsettings", "characterspawn" }),
            ("Siege & Combat",    new[] { "siege", "mangonel", "ballista", "ram", "ladder", "tower", "deployment", "wallsegment", "castlegate", "weapon", "blockade" }),
            ("AI & Navigation",   new[] { "patrol", "tactical", "strategic", "fightarea", "commonarea", "navigation", "road", "flee", "path" }),
            ("Usable Points",     new[] { "usable", "chair", "standingpoint", "passage", "use" }),
            ("Areas & Volumes",   new[] { "volume", "barrier", "box", "region", "marker", "zone", "boundary" }),
            ("Visual & Mesh",     new[] { "mesh", "destructable", "destructible", "material", "flag", "rope", "sail", "cloth", "visual" }),
            ("Naval",             new[] { "ship", "naval", "water", "float", "oar", "plank" }),
        };

        private static string Categorise(string name) {
            string lower = name.ToLowerInvariant();
            foreach ((string category, string[] keywords) in CategoryRules) {
                foreach (string keyword in keywords) {
                    if (lower.Contains(keyword)) return category;
                }
            }
            return "Other";
        }

        private static List<ScriptDefinition> Load() {
            var result = new List<ScriptDefinition>();
            string path = ResolvePath();

            if (path.Length == 0) {
                TraceLogger.Write(nameof(ScriptCatalog),
                    "script_catalog.xml not found. Script attachment will have nothing to offer; " +
                    "run tools/build_script_catalog.ps1 and redeploy.");
                return result;
            }

            try {
                var doc = new XmlDocument();
                doc.Load(path);

                XmlNodeList? scriptNodes = doc.SelectNodes("/ScriptCatalog/Script");
                if (scriptNodes != null) {
                    foreach (XmlNode scriptNode in scriptNodes) {
                        if (!(scriptNode is XmlElement scriptEl)) continue;

                        string name = scriptEl.GetAttribute("name");
                        if (name.Length == 0) continue;

                        var definition = new ScriptDefinition {
                            Name = name,
                            Uses = ParseInt(scriptEl.GetAttribute("uses")),
                            Category = Categorise(name),
                        };

                        foreach (XmlNode variableNode in scriptEl.ChildNodes) {
                            if (!(variableNode is XmlElement variableEl)) continue;

                            var variable = new ScriptVariable {
                                Name = variableEl.GetAttribute("name"),
                                Type = Fallback(variableEl.GetAttribute("type"), "string"),
                                Default = variableEl.GetAttribute("default"),
                                Samples = variableEl.GetAttribute("samples"),
                                Uses = ParseInt(variableEl.GetAttribute("uses")),
                            };

                            foreach (XmlNode valueNode in variableEl.ChildNodes) {
                                if (!(valueNode is XmlElement valueEl)) continue;
                                string text = valueEl.GetAttribute("text");
                                if (text.Length == 0) continue;
                                variable.Presets.Add(new ScriptPreset {
                                    Text = text,
                                    Uses = ParseInt(valueEl.GetAttribute("uses")),
                                    Scenes = ParseInt(valueEl.GetAttribute("scenes")),
                                });
                            }

                            definition.Variables.Add(variable);
                        }

                        result.Add(definition);
                    }
                }

                TraceLogger.Write(nameof(ScriptCatalog),
                    $"Loaded {result.Count} scripts from '{IOPath.GetFileName(path)}' " +
                    $"({result.Sum(s => s.Variables.Count)} variables).");
            } catch (Exception ex) {
                TraceLogger.WriteException(nameof(ScriptCatalog), $"Failed to parse '{path}'", ex);
            }

            return result.OrderByDescending(s => s.Uses).ToList();
        }

        private static int ParseInt(string value) => int.TryParse(value, out int parsed) ? parsed : 0;

        private static string Fallback(string value, string fallback) =>
            string.IsNullOrWhiteSpace(value) ? fallback : value;

        private static string ResolvePath() {
            foreach (string candidate in new[] {
                IOPath.Combine(BasePath.Name, "Modules", "CustomSceneCreator", "ModuleData", "script_catalog.xml"),
                IOPath.Combine(BasePath.Name, "Modules", "CustomSceneCreator", "_Module", "ModuleData", "script_catalog.xml"),
            }) {
                if (System.IO.File.Exists(candidate)) return candidate;
            }
            return "";
        }
    }
}
